/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        implementation("org.slf4j:slf4j-simple:2.0.6")
        implementation("org.springframework.boot:spring-boot-starter-validation:2.3.1.RELEASE")
        implementation("org.jetbrains.kotlin:kotlin-reflect:1.7.21")
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.22")
        implementation("org.springframework:spring-tx:6.0.3")
        implementation("javax.validation:validation-api:2.0.1.Final")

    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
